name: Build
on:
  merge_group:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          # we want to use whatever is in the `nixpkgs` input
          install_url: https://releases.nixos.org/nix/nix-2.11.1/install
      - uses: cachix/cachix-action@v12
        with:
          name: iliana
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch origin refs/notes/nix-store:refs/notes/nix-store
          trap "git push origin refs/notes/nix-store" EXIT
          ./x.py ci
