name: Build
on:
  merge_group:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: tailscale/github-action@8b804aa882ac3429b804a2a22f9803a2101a0db9
        env:
          TS_EXPERIMENT_OAUTH_AUTHKEY: true
        with:
          authkey: '${{ secrets.TS_OAUTH_CLIENT_SECRET }}'
          version: 1.40.1
          args: --advertise-tags tag:nix-build-ci
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          # we want to use whatever is in the `nixpkgs` input
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
          extra_nix_config: "builders = ssh://build@lernie x86_64-linux - 2 1 kvm,nixos-test kvm c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUgraW1WRG5MWWxCTUFFQytIUFF5Z1ZTSHNWWFZoOEVobE5pajgwUE56ZVA="
      - uses: cachix/cachix-action@v12
        with:
          name: iliana
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch origin refs/notes/nix-store:refs/notes/nix-store
          trap "git push origin refs/notes/nix-store" EXIT
          ./x.py ci
