name: Build
on:
  merge_group:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: iliana
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: ./x.py ci
