name: update-flake-lock
on:
  workflow_dispatch: # allows running this workflow manually
  schedule:
    - cron: '27 13 * * *' # runs every day at 13:27 UTC
jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v2
      - uses: DeterminateSystems/update-flake-lock@v19
        with:
          pr-labels: |
            dependencies
            automated
